name: Erlang CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  build_and_test:

    runs-on: ubuntu-22.04

    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ["24.0", "25.0"]

    steps:
    - uses: actions/checkout@v2.0.0
    - uses: erlef/setup-beam@v1.16.0
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: '3.16.1'
    - name: Compile
      run: make
    - name: Run xref
      run: make xref
    - name: Run elvis
      run: make elvis_rock
    - name: Run dialyzer
      run: make dialyze
    - name: Run proper tests
      run: make proper

  release:
    if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'no-release:') == false
    needs: build_and_test
    runs-on: ubuntu-22.04
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
