---
name: ci

on:
  # for feature branches and releases
  push:

concurrency:
  group: ${{ (github.ref != 'refs/heads/master') && format('{0}-{1}', github.ref, github.workflow) || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build_and_test:

    runs-on: ubuntu-22.04

    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ["26", "27"]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
      with:
        otp-version: ${{ matrix.otp }}
        rebar3-version: '3.24'
    - name: Compile
      run: make
    - name: Run xref
      run: make xref
    - name: Run elvis
      run: make elvis_rock
    - name: Run dialyzer
      run: make dialyze
    - name: Run proper tests
      run: make proper

  release:
    if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'no-release:') == false
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Bump version and push tag
      id: tag-version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        release_branches: master

    - name: Create a GitHub release
      run: |
        if ! command -v gh >/dev/null 2>&1; then
          curl -sS https://webi.sh/gh | sh
        fi
        gh release create ${{ steps.tag-version.outputs.new_tag }} --generate-notes --latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
