name: Erlang CI

on: [push]

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Run erl
      run: |
        which erl
        erl -eval 'erlang:display({otp_release, erlang:system_info(otp_release)}), halt().' -noshell
    - name: Run rebar3
      run: |
        which rebar3
        rebar3 version
    - name: Compile
      run: make
    - name: Run xref
      run: make xref
    - name: Run elvis
      run: make elvis_rock
    - name: Run proper tests
      run: make proper

  dialyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run dialyzer
      run: make dialyze
